services:
  http-server:
    build: ./http_server/
    ports:
      - 2718:2718
    env_file:
      - ./.env
    environment:
      - REDIS_HOST = valkey
    command: "python3 litestar_server.py"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.http-server.rule=Host(`${DOMAIN:-marker.kessler.xyz}`) && PathPrefix(`/api`) || PathPrefix(`/schema`)"
      - "traefik.http.routers.http-server.entrypoints=websecure"
      - "traefik.http.routers.http-server.tls.certresolver=myresolver"
  valkey:
    hostname: valkey
    image: valkey/valkey:7.2.5
    expose:
      - 6379
    ports:
      - "6379:6379"
    volumes:
      - ./volumes/valkey-data:/data
  reverse-proxy:
    # official image
    image: traefik:v3.0
    command:
      # - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      # - "--certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.myresolver.acme.email=mbright@kessler.xyz"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
      - "${PROXY_UI_PORT:-8083}:8080"
    volumes:
      - "${VOLUMES_DIRECTORY:-./volumes}/letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
