services:
  marker:
    build: .
    mem_limit: ${MEM_LIMIT:-20gb}
    memswap_limit: ${MEM_LIMIT:-20gb}
    deploy:
      resources:
        limits:
          memory: ${MEM_LIMIT:-20gb}
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["0"]
              capabilities: [gpu]
      mode: replicated
      replicas: ${CONTAINER_REPLICAS}
    env_file:
      - ./.env
    command: "python3 marker_slave_node.py"
    restart: always
