services:
  marker:
    build: .
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["0"]
              capabilities: [gpu]
    environment:
      - MARKER_PORT = 2718
    ports:
      - 2718:2718
    expose:
      - 2718
    volumes:
      - "./volumes/in:/app/in"
      - "./volumes/out:/app/out"
    command: "poetry run python3 new-server.py"
    restart: always
