services:
  marker-1:
    build: .
    mem_limit: 30gb
    memswap_limit: 30gb
    deploy:
      resources:
        limits:
          memory: 30gb
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["0"]
              capabilities: [gpu]
    env_file:
      - ./.env
    command: "python3 new_server.py"
    restart: always
  marker-2:
    build: .
    mem_limit: 30gb
    memswap_limit: 30gb
    deploy:
      resources:
        limits:
          memory: 30gb
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["0"]
              capabilities: [gpu]
    env_file:
      - ./.env
    command: "python3 new_server.py"
    restart: always
