services:
  http-server:
    build: ./http_server/
    ports:
      - 2718:2718
    expose:
      - 2718
    environment:
    command: "python3 litestar_server.py"
  marker:
    build: .
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["0"]
              capabilities: [gpu]
    environment:
      - MARKER_PORT=2718
      - REDIS_HOST=redis
      - REDIS_STATUS_KEY="request_status"
      - REDIS_BACKGROUND_QUEUE_KEY ="request_queue_background"
      - REDIS_PRIORITY_QUEUE_KEY ="request_queue_priority"

    command: "poetry run python3 new_server.py"
    restart: always

  redis:
    image: "redis:alpine"
    expose:
      - 6379
    ports:
      - "6379:6379"
    volumes:
      - ./volumes/redis-data:/data
