services:
  http-server:
    build: ./http_server/
    ports:
      - 2718:2718
    expose:
      - 2718
    env_file:
      - .env
    command: "python3 litestar_server.py"
  marker:
    build: .
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["0"]
              capabilities: [gpu]
    env_file:
      - .env
    command: "python3 new_server.py"
    restart: always

  redis:
    image: "redis:alpine"
    expose:
      - 6379
    ports:
      - "6379:6379"
    volumes:
      - ./volumes/redis-data:/data
