services:
  marker:
    build: .
    mem_limit: ${MEM_LIMIT:-30gb}
    memswap_limit: ${MEM_LIMIT:-30gb}
    deploy:
      mode: replicated
      replicas: ${REPLICAS:-2}
      resources:
        limits:
          memory: ${MEM_LIMIT:-30gb}
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["0"]
              capabilities: [gpu]
    env_file:
      - ./.env
    command: "python3 new_server.py"
    restart: always
