# frpc.toml
serverAddr = "frps-testing.tail4a273.ts.net"
serverPort = 7000

# [[proxies]]
# name = "webserver-insecure"
# type = "http"
# localPort = 80
# customDomains = ["frpmedia.kessler.xyz"]

[[proxies]]
name = "marker-headserver-insecure"
type = "http"
localPort = 2718
# localIP = "reverse-proxy"
customDomains = ["markerbackup.kessler.xyz", "marker.kessler.xyz"]
